- name: add APT key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add repository
  apt_repository: >
    repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main'
    state=present

- name: install package
  apt: pkg=logstash state=installed
  notify: start logstash

#make sure the logstash is started
- name: make sure logstash is started
  service: name=logstash state=restarted
