- name: add APT key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: add repository
  apt_repository: >
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present
- name: install package
  apt: pkg=newrelic-sysmond
  notify: restart newrelic-sysmond

- name: generate config
  template: >
    src=nrsysmond.cfg.j2
    dest=/etc/newrelic/nrsysmond.cfg
    owner=root
    group=newrelic
    mode=0640
  notify: restart newrelic-sysmond
