---

- name: add APT key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add repository
  apt_repository: >
    repo='deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main'
    state=present

- name: install elasticsearch
  apt: name=elasticsearch state=installed
  notify: start elasticsearch

- name: make elasticsearch to be system service
  shell: update-rc.d elasticsearch defaults 95 10

- name: make sure elasticsearch is started
  service: name=elasticsearch state=restarted
